config/routes.rb
Rails.application.routes.draw do
  root 'home#top'
  resources :comment
  get 'comment/confirm'
  post 'comment/confirm'
  get 'comment/excute'
  post 'comment/excute'
  post 'home/create'

  get 'home/signup'
  post 'home/signup'

  get 'home/login'
  post 'home/login'
  post 'home/logout'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/payload.rb
class Payload < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comment_controller.rb
class CommentController < ApplicationController
  require "http"
  skip_before_action :verify_authenticity_token
  before_action :prepare

  def index
    return render :create if params[:comment] == ""
    @comment = Comment.where(user_id: @id)
    return render :show if params[:format].nil? && params[:comment].nil?
    if params[:format] == 'attack'
      return redirect_to comment_index_path, :alert => 'コメントを最低ひとつは作成してください' if @comment == []
      forms = []
      @payload.each do |payload|
        forms.push([payload.memo, payload.thread_num])
      end
      @forms = forms
      render :index
    end
  end

  def show
  end

  def edit
    value = Comment.find(params[:id])
    @comment = value.text
    return flash.now[:alert] = '入力してください' if params[:commit] && params[:comment] == ""
    if params[:id] && params[:comment]
      comment = Comment.find(params[:id])
      comment.text = params[:comment]
      redirect_to comment_index_path if comment.update(text: comment.text)
    end
  end

  def create
    if params[:comment]
      return redirect_to comment_index_path(:comment => ""), :alert => '入力してください' if params[:comment] == ""
      param = params[:comment]
      comment = Comment.new(comment_params)
      comment.text = param
      comment.user_id = @id
      redirect_to comment_index_path if comment.save
    else
    end
  end

  def confirm
    return redirect_to comment_index_path(:format => 'attack') , :alert => '投稿コメントを選択してください' unless params[:check_box]
    return redirect_to comment_index_path unless params[:select] || params[:check_box] || params[:min]
    thread = Payload.find_by(thread_num: params[:select])
    @thread = thread.memo
    text = []
    params[:check_box].each do |checks|
      text.push(Comment.find(checks).text)
    end
    @text = text
    @min = params[:min]
  end

  def excute
    return redirect_to comment_index_path unless params[:thread] || params[:text] || params[:min]
    thread = Payload.find_by(memo: params[:thread])
    thread = thread.thread_num
    text = []
    name = '匿名'
    params[:text].each do |checks|
      text.push(checks)
    end
    min = params[:min]
    if text.size > 1
      text.each_with_index do |texts, index|
        # 荒らし防止のためドメインは割愛
        uri = "https://ここにドメイン/post_comment/?mode=execute&thread_no=" + thread.to_s + "&nickname=" + name.to_s + "+&comment=" + texts
        p uri
        response = HTTP.get(uri)
        puts "success!" if response.code == 200
        p min.to_s + '分間隔'
        count = index + 1
        p count.to_s + '回目'
        break if index + 1 == text.size
        sleep min.to_i * 60
      end
    else
      # 荒らし防止のためドメインは割愛
      uri = "https://ここにドメイン/post_comment/?mode=execute&thread_no=" + thread.to_s + "&nickname=" + name.to_s + "&comment=" + text[0].to_s
      p uri
      response = HTTP.get(uri)
      puts "success!" if response.code == 200
    end
    redirect_to comment_index_path, :notice => '投稿が終わりました'
  end

  def destroy
    p 'passed destroy'
    if params[:id]
      Comment.find(params[:id]).destroy
      redirect_to comment_index_path
    end
  end

  private
  def comment_params
    params.permit(:text)
  end

  protected
  def prepare
    return redirect_to root_path if session[:user_id].nil?
    @comment = Comment.all
    @payload = Payload.all
    user = User.find_by_email(session[:user_id])
    @name = user.name
    @id = user.id
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
    p 'passed top'
    p session[:user_id] if session[:user_id]
    if session[:user_id]
      user = User.find_by_email(session[:user_id])
      @name = user.name
      p @name
    end
  end

  def signup
    @confirm = params if params[:name] && params[:email] && params[:password] && params[:password_confirm]
    @name = nil unless @confirm
    @email = nil unless @confirm
    @name = params[:df_name] if params[:df_name]
    @email = params[:df_email] if params[:df_email]
    return redirect_to home_signup_path(:df_name => @confirm[:name], :df_email => @confirm[:email]), :alert => '名前を入力してください' if params[:name] == "" && @confirm
    return redirect_to home_signup_path(:df_name => @confirm[:name], :df_email => @confirm[:email]), :alert => 'メールアドレスを入力して下さい' if params[:email] == "" && @confirm
    return redirect_to home_signup_path(:df_name => @confirm[:name], :df_email => @confirm[:email]), :alert => 'パスワードを入力して下さい' if params[:password] == "" && @confirm
    redirect_to home_signup_path(:df_name => @confirm[:name], :df_email => @confirm[:email]), :alert => '確認用パスワードが一致しません' if params[:password] != params[:password_confirm] && @confirm
  end

  def create
    user = User.new(signup_params)
    user.name = params[:name]
    user.email = params[:email]
    user.password_digest = params[:password]
    return redirect_to root_path, :notice => '登録しました' if user.save
    redirect_to root_path, :notice => '登録に失敗しました'
  end

  def login
    if params[:email] && params[:password]
      return redirect_to home_login_path, :alert => 'メールアドレスを入力してください' if params[:email] == "" && params[:password] == ""
      return redirect_to home_login_path, :alert => 'パスワードを入力してください' if params[:email] && params[:password] == ""
      return redirect_to home_login_path, :alert => 'メールアドレスを入力してください' if params[:email] == "" && params[:password]
      if User.find_by(email: params[:email], password_digest: params[:password])
        user = User.find_by(email: params[:email])
        session[:user_id] = user.email
        redirect_to root_path, :notice => 'ログインできました'
      else
        redirect_to home_login_path, :alert => 'メールアドレスまたはパスワードが一致しません'
      end
    end
  end

  def logout
    session[:user_id] = nil
    redirect_to root_path, :notice => 'ログアウトしました'
  end

  private
  def signup_params
    params.permit(:name, :email, :password_digest)
  end
end

app/views/comment/_prof.html.erb
<p>ようこそ！ <%= @name %>様  <%= button_to "log out", home_logout_path, method: :post, class: 'btn btn-success btn-sm' %></p>

app/views/comment/confirm.html.erb
<h1>Confirm</h1>
<h3>投稿スレッド</h3>
<%= @thread %>
<br>
<h3>コメント（順番）</h3>
<% @text.each_with_index do |texts, index| %>
  <%= index + 1 %>番目の投稿：  <%= texts %>
  <br>
<% end %>
<br>
<h3>投稿間隔</h3>
<%= @min %>分
<br><br>
<%= button_to '投稿！', comment_excute_path(:thread => @thread, :text => @text, :min => @min) %>
<br><br>
<%= link_to '戻る', comment_index_path %>

app/views/comment/create.html.erb
<h1>Create comment</h1>
<h3 style="color: red"><%= alert %></h3>
<%= form_with url: comment_index_path, method: :post do |form| %>
  <%= form.text_field :comment %>
  <%= form.submit 'confirm', class: 'btn btn-secondary btn-sm' %>
<% end %>
<%= link_to "戻る", comment_index_path %>

app/views/comment/destroy.html.erb
<h1>Comment#destroy</h1>
<p>Find me in app/views/comment/destroy.html.erb</p>

app/views/comment/edit.html.erb
<h1>Editting comment</h1>
<h3 style="color: red"><%= alert %></h3>
<%= form_with url: edit_comment_path(:id => params[:id]), method: :get do |form| %>
  <%= form.text_field :comment, value: @comment %>
  <%= form.submit 'confirm', class: 'btn btn-secondary btn-sm' %>
<% end %>
<p><%= link_to '戻る', comment_index_path %></p>

app/views/comment/index.html.erb
<h1>Attack lists</h1>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<!--  <h6 style="color: red" class="alert alert-danger"><svg class="bi flex-shrink-0 me-2" width="24" height="24"><use xlink:href="#exclamation-triangle-fill"/></svg><%#= alert %></h6>-->
<% end %>
  <li class="list-group-item list-group-item-secondary">
  <h5>投稿スレッド</h5>
  <%= form_with url: comment_confirm_path, method: :post do |form| %>
    <%= form.select :select, @forms %>
  </li>
  <li class="list-group-item list-group-item-info">
    <h5>投稿コメント</h5><h6>(※チェックした上から順番に投稿されます)</h6>
    <% @comment.each do |comment| %>
      <%= form.check_box :check_box, {multiple: true}, comment.id, nil %>
      <%= comment.text %>
      <br />
    <% end %>
  </li>
  <li class="list-group-item list-group-item-danger">
  <h5>投稿間隔</h5>
    <%= form.select :min, [['1分', 1], ['3分', 3],['5分', 5], ['10分', 10]] %>
  </li>
    <div style="text-align: center; padding-top: 10px"><%= form.submit '確認', class: 'btn btn-warning' %></div>
  <% end %>
<br><br>
<%= link_to 'BACK TO LISTS', comment_index_path %>

app/views/comment/show.html.erb
<li class="list-group-item list-group-item-info">
  <%= render partial: 'prof'%>
</li>
<br>
<h2>Comments list</h2>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>
<% if @comment %>
  <% @comment.each do |comment| %>
    <ul class="list-group">
      <li class="list-group-item"><%= comment.text %></li>
    </ul>
    <div style="text-align: right; padding-top: 5px">
    <div style="float: right; padding-left: 5px"><%= button_to 'edit', edit_comment_path(:id => comment.id), method: :get, class: 'btn btn-outline-success btn-sm' %></div>
    <div><%= button_to 'delete', comment_path(:id => comment.id), method: :delete, class: 'btn btn-outline-danger btn-sm' %></div>
    </div>
    <br>
  <% end %>
<% end %>

<div style="text-align: right">
  <%= button_to '新規コメント作成', comment_index_path, method: :post, class: 'btn btn-secondary btn-sm' %>
</div>
<br>
<div style="text-align: right">
  <%= button_to '投稿する', comment_index_path('attack'), method: :get, class: 'btn btn-warning' %>
</div>

app/views/home/login.html.erb
<div style="text-align: center; padding-top: 50px;">
<h1>Log in</h1>
<p style="color: red"> <%= alert %> </p>
<%= form_with url: home_login_path , method: :post do |form| %>
  <p>メールアドレス<br><%= form.text_field :email %></p>
  <p>パスワード<br><%= form.text_field :password %></p>
  <p><%= form.submit 'log in', class: 'btn btn-success btn-sm'%></p>
  <% end %>
</div>

app/views/home/signup.html.erb
<div style="text-align: center; padding-top: 50px;">
  <h2>Sign up</h2>
  <p style="color: red"> <%= alert %> </p>
  <% unless @confirm %>
    <%= form_with url: home_signup_path, method: :post do |form| %>
      <p>名前<br><%= form.text_field :name, value: @name %></p>
      <p>email<br><%= form.text_field :email, value: @email %></p>
      <p>パスワード<br><%= form.text_field :password %></p>
      <p>パスワード（確認）<br><%= form.text_field :password_confirm %></p>
      <p><%= form.submit '確認', class: 'btn btn-success btn-sm'%></p>
    <% end %>
  <% end %>

  <% if @confirm %>
    <p>名前<br><%= @confirm[:name] %></p>
    <p>email<br><%= @confirm[:email] %></p>
    <p>パスワード<br><%= @confirm[:password_confirm] %></p>
    <p><%= button_to "登録", home_create_path(:name => @confirm[:name], :email => @confirm[:email], :password => @confirm[:password_confirm]), method: :post, class: 'btn btn-success btn-sm' %></p>
  <% end %>
</div>

app/views/home/top.html.erb
<div style="text-align: center; padding-top: 50px;">
  <h2>Hello</h2>
  <h5 style="color: red"> <%= notice %> </h5>
  <% if @name %>
    <p>ようこそ！ <%= @name %>様</p>
    <p><%= button_to "log out", home_logout_path, method: :post, class: 'btn btn-success btn-sm'%></p>
    <p><%= link_to "コメントリストへ", comment_index_path %></p>
  <% else %>
    <p><%= link_to "sign up", home_signup_path, class: 'btn btn-outline-primary' %></p>
    <p><%= link_to "log in", home_login_path, class: 'btn btn-outline-secondary' %></p>
  <% end %>
</div>